export default {
    CONSTRUCTION_POINTS_PER_BUILDER: 10,
    CONSTRUCTION_POINT_TTL: 100,
    CPU_ADJUST: 0.05,
    CPU_BOOST: 0,
    CPU_BUFFER: 100,
    CPU_MINIMUM: 0.30,
    SOURCE_POINT_TTL: 100
};
